// flow-typed signature: be09e68d6a93150d3b0ccbaeff3a41e3
// flow-typed version: <<STUB>>/react-mic_v^9.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mic/es/components/ReactMic' {
  declare module.exports: any;
}

declare module 'react-mic/es/index' {
  declare module.exports: any;
}

declare module 'react-mic/es/libs/AudioContext' {
  declare module.exports: any;
}

declare module 'react-mic/es/libs/AudioPlayer' {
  declare module.exports: any;
}

declare module 'react-mic/es/libs/MicrophoneRecorder' {
  declare module.exports: any;
}

declare module 'react-mic/es/libs/Visualizer' {
  declare module.exports: any;
}

declare module 'react-mic/lib/components/ReactMic' {
  declare module.exports: any;
}

declare module 'react-mic/lib/index' {
  declare module.exports: any;
}

declare module 'react-mic/lib/libs/AudioContext' {
  declare module.exports: any;
}

declare module 'react-mic/lib/libs/AudioPlayer' {
  declare module.exports: any;
}

declare module 'react-mic/lib/libs/MicrophoneRecorder' {
  declare module.exports: any;
}

declare module 'react-mic/lib/libs/Visualizer' {
  declare module.exports: any;
}

declare module 'react-mic/umd/react-mic' {
  declare module.exports: any;
}

declare module 'react-mic/umd/react-mic.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mic/es/components/ReactMic.js' {
  declare module.exports: $Exports<'react-mic/es/components/ReactMic'>;
}
declare module 'react-mic/es/index.js' {
  declare module.exports: $Exports<'react-mic/es/index'>;
}
declare module 'react-mic/es/libs/AudioContext.js' {
  declare module.exports: $Exports<'react-mic/es/libs/AudioContext'>;
}
declare module 'react-mic/es/libs/AudioPlayer.js' {
  declare module.exports: $Exports<'react-mic/es/libs/AudioPlayer'>;
}
declare module 'react-mic/es/libs/MicrophoneRecorder.js' {
  declare module.exports: $Exports<'react-mic/es/libs/MicrophoneRecorder'>;
}
declare module 'react-mic/es/libs/Visualizer.js' {
  declare module.exports: $Exports<'react-mic/es/libs/Visualizer'>;
}
declare module 'react-mic/lib/components/ReactMic.js' {
  declare module.exports: $Exports<'react-mic/lib/components/ReactMic'>;
}
declare module 'react-mic/lib/index.js' {
  declare module.exports: $Exports<'react-mic/lib/index'>;
}
declare module 'react-mic/lib/libs/AudioContext.js' {
  declare module.exports: $Exports<'react-mic/lib/libs/AudioContext'>;
}
declare module 'react-mic/lib/libs/AudioPlayer.js' {
  declare module.exports: $Exports<'react-mic/lib/libs/AudioPlayer'>;
}
declare module 'react-mic/lib/libs/MicrophoneRecorder.js' {
  declare module.exports: $Exports<'react-mic/lib/libs/MicrophoneRecorder'>;
}
declare module 'react-mic/lib/libs/Visualizer.js' {
  declare module.exports: $Exports<'react-mic/lib/libs/Visualizer'>;
}
declare module 'react-mic/umd/react-mic.js' {
  declare module.exports: $Exports<'react-mic/umd/react-mic'>;
}
declare module 'react-mic/umd/react-mic.min.js' {
  declare module.exports: $Exports<'react-mic/umd/react-mic.min'>;
}
